disabled: false
reporter:
  logSpans: true
  endpoint: http://prismdevtest.umvm.nutanix.com:14268/api/traces
sampler:
  samplingServerURL: http://prismdevtest.umvm.nutanix.com:5778/sampling  
  param: 1
